name: Rust Build and Publish

on:
  push:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build and test (Linux)
      run: cargo build --release && cargo test

    - name: Publish (Linux)
      run: cargo publish
      env:
        CARGO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable-x86_64-pc-windows-msvc

    - name: Build and test (Windows)
      run: cargo build --release && cargo test

    - name: Publish (Windows)
      run: cargo publish
      env:
        CARGO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
